time= input('Enter the digit-time(hour:minute:second):')
table1=str.maketrans('0','.')
table2=str.maketrans('1','-')
num=time.split(':')
list1=[]
for i in num:
    each=list(i)
    if len(each)==1:
        each.append('0')
        each=list(reversed(each))
    list1.append(each)
h1='{:b}'.format(int(list1[0][0]))
h2='{:b}'.format(int(list1[0][1]))
m1='{:b}'.format(int(list1[1][0]))
m2='{:b}'.format(int(list1[1][1]))
s1='{:b}'.format(int(list1[2][0]))
s2='{:b}'.format(int(list1[2][1]))
ch1='0'*(2-len(h1))
ch2='0'*(4-len(h2))
cm1='0'*(3-len(m1))
cm2='0'*(4-len(m2))
cs1='0'*(3-len(s1))
cs2='0'*(4-len(s2))
fina='{}{} {}{} : {}{} {}{} : {}{} {}{}'.format(ch1,h1,ch2,h2,cm1,m1,cm2,m2,cs1,s1,cs2,s2)
final=fina.translate(table1)
final=final.translate(table2)
print('The converted morse-time is: {}'.format(final))
